"""add User Room Booking tables

Revision ID: 1df1d9d795b9
Revises: c60c6af769a3
Create Date: 2025-06-20 07:53:19.206671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '1df1d9d795b9'
down_revision: Union[str, Sequence[str], None] = 'c60c6af769a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'rooms',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('hotel_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('price', sa.Integer(), nullable=False),
        sa.Column('services', sa.JSON(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('image_id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('hashed_password', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'Bookings',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('room_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('date_from', sa.Date(), nullable=False),
        sa.Column('date_to', sa.Date(), nullable=False),
        sa.Column('price', sa.Integer(), nullable=False),
        sa.Column('total_days', sa.Integer(), sa.Computed('date_to - date_from + 1', persisted=True), nullable=False),
        sa.Column('total_cost', sa.Integer(), sa.Computed('price * (date_to - date_from + 1)', persisted=True), nullable=False),
        sa.ForeignKeyConstraint(['room_id'], ['rooms.id']),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id')
    )

    # Добавляем изменение типа данных для поля image_id
    op.alter_column(
        'rooms',
        'image_id',
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=sa.Integer(),
        postgresql_using='image_id::integer'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Откат обратно к JSON типу.
    op.alter_column(
        'rooms',
        'image_id',
        existing_type=sa.Integer(),
        type_=postgresql.JSON(astext_type=sa.Text()),
        postgresql_using='image_id::json'
    )

    # Удаление созданных таблиц
    op.drop_table('Bookings')
    op.drop_table('users')
    op.drop_table('rooms')
    # ### end Alembic commands ###