"""empty message

Revision ID: c4b36ba80116
Revises: 1df1d9d795b9
Create Date: 2025-06-20 08:23:33.366851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4b36ba80116'
down_revision: Union[str, Sequence[str], None] = '1df1d9d795b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('total_days', sa.Integer(), sa.Computed('date_to - date_from + 1', persisted=True), nullable=False),
    sa.Column('total_cost', sa.Integer(), sa.Computed('price * (date_to - date_from + 1)', persisted=True), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Bookings')
    op.alter_column('rooms', 'image_id',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'image_id',
               existing_type=sa.Integer(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.create_table('Bookings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date_from', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('date_to', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_days', sa.INTEGER(), sa.Computed('((date_to - date_from) + 1)', persisted=True), autoincrement=False, nullable=False),
    sa.Column('total_cost', sa.INTEGER(), sa.Computed('(price * ((date_to - date_from) + 1))', persisted=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('Bookings_room_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('Bookings_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('Bookings_pkey'))
    )
    op.drop_table('bookings')
    # ### end Alembic commands ###
